# help

## engineering
# test
test:
	pytest

# test-coverage:
# 	pytest --cov={{}} --cov-report html --cov-config .coveragerc

# flake8
lint:
	flake8 --exclude=doc,

# mypy

## analysis

# directories
DIR_DATA := data
DIR_BUILD := build
DIR_BIN := $(DIR_BUILD)/bin
DIR_BLEND := $(DIR_BUILD)/blend
DIR_FEATURE := $(DIR_BUILD)/feature
DIR_METRIC := $(DIR_BUILD)/metric
DIR_MODEL := $(DIR_BUILD)/model

