# help


# install
install:
	pip install .

develop:
	pip install -e .

# test
test:
	pytest

test-coverage:
	pytest --cov=src --cov-report html --cov-config .coveragerc

# flake8
lint:
	flake8 --exclude=doc,

# clean



# mypy

## analysis

# directories
DIR_DATA := data
DIR_RAW_DATA := $(DIR_DATA)/raw
DIR_INPUT_DATA := $(DIR_DATA)/input
DIR_WORKING_DATA := $(DIR_DATA)/working
DIR_OUTPUT_DATA := $(DIR_DATA)/output
DIR_FEATURE_DATA := $(DIR_DATA)/feature

DIR_MODEL := models

# load data

# preprocess

# feature

# model

# cleanup
